# Generated by Django 4.2.5 on 2023-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_fee', models.IntegerField(default=0)),
                ('submited_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
