# Generated by Django 4.2.5 on 2023-10-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('school_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('freq_month', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('defaultor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='fee_info',
        ),
    ]
